spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  #  liquibase:
  #    analytics-enabled: true
  #    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  banner:
    location: classpath:prod-banner.txt

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis
    redis:
      time-to-live: 5m
      cache-null-values: false
      key-prefix: ${REDIS_PREFIX}

minio:
  endpoint: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket:
    name: ${MINIO_BUCKET_NAME}

logging:
  level:
    org.springframework.cache: DEBUG