spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yml'
    contexts: dev
    drop-first: false
    default-schema: public
    liquibase-schema: public
    database-change-log-lock-table: 'databasechangeloglock'
    database-change-log-table: 'databasechangelog'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  banner:
    location: classpath:dev-banner.txt

minio:
  endpoint: http://localhost:9001
  access-key: minioadmin
  secret-key: minioadmin
  bucket:
    name: employee